### ISSUE TITLE
train got an error

### ISSUE THREAD

**Issue by jayjayadmire** [bozliu/video-captioning#1]
After extracted my videos' features, I excute train.py then it happended an error.
```
/home/lab-space/personal/jayjia/video-captioning/dataset/VideoCaptionDataset.py:66: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  videoSequences = np.array(videoSequences)
/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:154: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
====== Train Model ======
Traceback (most recent call last):
  File "/home/mmifhost/.pycharm_helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/mmifhost/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lab-space/personal/jayjia/video-captioning/train.py", line 244, in <module>
    train(i)
  File "/home/lab-space/personal/jayjia/video-captioning/train.py", line 46, in train
    outputs, _ = model(features, decoderInput)
  File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
python-BaseException
  File "/home/lab-space/personal/jayjia/video-captioning/model/Seq2Seq.py", line 48, in forward
    video_output,init_states=self.encoder(video_features)
  File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lab-space/personal/jayjia/video-captioning/model/Seq2Seq.py", line 17, in forward
    output,states=self.encoderLSTM(input)
  File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 689, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 632, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 207, in check_input
    self.input_size, input.size(-1)))
RuntimeError: input.size(-1) must be equal to input_size. Expected 1024, got 50176
```

I have no idea to deal with it, could please tell me how to fix it?

**Comment by jayjayadmire** [comment]
I found the error in train.py at train(epoch) function.
update this
```
        # features = features.view(features.size()[0], features.size()[3], -1)
        features = features.view(features.size()[0], -1, features.size()[2])
```
so I can train successfully.
But through 150 epoch, I got the bad performance.
Only use video.

**Comment by hugarlakhan** [comment]
![image](https://user-images.githubusercontent.com/90457379/146799483-24335cff-0af1-4247-a6e0-27e13367cd34.png)


Please provide these files. I am not getting these files.
Thank you

**Comment by bozliu** [comment]
Sorry, this is not an open source project
